/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Finals.CritterCode;

/**
 *
 * @author Kia
 */
public class GuideFrame extends javax.swing.JFrame {

    /**
     * Creates new form GuideFrames
     */
    public GuideFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_POSTER = new javax.swing.JPanel();
        jLabel_POSTER = new javax.swing.JLabel();
        jPanel_GUIDEBOOK = new javax.swing.JPanel();
        jLabel_GUIDEBOOK = new javax.swing.JLabel();
        jPanel_CREDITS = new javax.swing.JPanel();
        jLabel_CREDITS = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(147, 119, 198));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 55, 136), 4));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel_POSTER.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kia\\Documents\\NetBeansProjects\\ICT 115\\src\\Finals\\Images\\CRITTERCODE_POSTER.png")); // NOI18N
        jLabel_POSTER.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 55, 136), 4));

        javax.swing.GroupLayout jPanel_POSTERLayout = new javax.swing.GroupLayout(jPanel_POSTER);
        jPanel_POSTER.setLayout(jPanel_POSTERLayout);
        jPanel_POSTERLayout.setHorizontalGroup(
            jPanel_POSTERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_POSTERLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_POSTER, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_POSTERLayout.setVerticalGroup(
            jPanel_POSTERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_POSTER, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CRITTER CODE", jPanel_POSTER);

        jPanel_GUIDEBOOK.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N

        jLabel_GUIDEBOOK.setFont(new java.awt.Font("Dialog", 0, 32)); // NOI18N
        jLabel_GUIDEBOOK.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kia\\Documents\\NetBeansProjects\\ICT 115\\src\\Finals\\Images\\4.png")); // NOI18N

        javax.swing.GroupLayout jPanel_GUIDEBOOKLayout = new javax.swing.GroupLayout(jPanel_GUIDEBOOK);
        jPanel_GUIDEBOOK.setLayout(jPanel_GUIDEBOOKLayout);
        jPanel_GUIDEBOOKLayout.setHorizontalGroup(
            jPanel_GUIDEBOOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_GUIDEBOOKLayout.createSequentialGroup()
                .addComponent(jLabel_GUIDEBOOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_GUIDEBOOKLayout.setVerticalGroup(
            jPanel_GUIDEBOOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_GUIDEBOOK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("GUIDE BOOK", jPanel_GUIDEBOOK);

        jPanel_CREDITS.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N

        jLabel_CREDITS.setFont(new java.awt.Font("Dialog", 0, 32)); // NOI18N
        jLabel_CREDITS.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kia\\Documents\\NetBeansProjects\\ICT 115\\src\\Finals\\Images\\2.png")); // NOI18N

        javax.swing.GroupLayout jPanel_CREDITSLayout = new javax.swing.GroupLayout(jPanel_CREDITS);
        jPanel_CREDITS.setLayout(jPanel_CREDITSLayout);
        jPanel_CREDITSLayout.setHorizontalGroup(
            jPanel_CREDITSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CREDITSLayout.createSequentialGroup()
                .addComponent(jLabel_CREDITS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_CREDITSLayout.setVerticalGroup(
            jPanel_CREDITSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_CREDITS, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CREDITS", jPanel_CREDITS);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kia\\Documents\\NetBeansProjects\\ICT 115\\src\\Finals\\Images\\5.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuideFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuideFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuideFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuideFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuideFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_CREDITS;
    private javax.swing.JLabel jLabel_GUIDEBOOK;
    private javax.swing.JLabel jLabel_POSTER;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_CREDITS;
    private javax.swing.JPanel jPanel_GUIDEBOOK;
    private javax.swing.JPanel jPanel_POSTER;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
